name: Build, Push Docker and Update Helm Chart

on:
  push:
    branches:
      - main

jobs:
  build_and_update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main repo
        uses: actions/checkout@v3

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.4

      - name: Install yq
        shell: bash
        run: |
          set -e
          YQ_VERSION=v4.44.3
          sudo wget -qO /usr/local/bin/yq "https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/yq_linux_amd64"
          sudo chmod +x /usr/local/bin/yq
          yq --version
          helm version

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract version tag
        id: vars
        shell: bash
        run: |
          set -e
          DOCKER_VERSION="1.0.${{ github.run_number }}-${GITHUB_SHA::7}"
          CHART_VERSION="1.0.${{ github.run_number }}"
          APP_VERSION="${CHART_VERSION}-${GITHUB_SHA::7}"
          echo "DOCKER_VERSION=$DOCKER_VERSION" >> $GITHUB_ENV
          echo "CHART_VERSION=$CHART_VERSION" >> $GITHUB_ENV
          echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV
          echo "Docker tag: $DOCKER_VERSION"
          echo "Chart version: $CHART_VERSION"
          echo "App version: $APP_VERSION"

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/delivery-app:${{ env.DOCKERHUB_VERSION }}

      - name: Checkout manifests repo (chart fuente)
        uses: actions/checkout@v3
        with:
          repository: ritatrcr/manifiestos-delivery-app
          token: ${{ secrets.PAT_HELMCHART }}
          path: manifiestos

      - name: Update Helm chart values.yaml image tag
        shell: bash
        run: |
          set -e
          cd charts/pedido-app
          yq eval ".image.tag = \"${DOCKER_VERSION}\"" -i values.yaml

      - name: Update Chart version in Chart.yaml
        shell: bash
        run: |
          set -e
          cd charts/pedido-app
          yq eval ".version = \"${CHART_VERSION}\"" -i Chart.yaml
          yq eval ".appVersion = \"${APP_VERSION}\"" -i Chart.yaml

      - name: Package Helm Chart
        shell: bash
        run: |
          set -e
          
          helm package charts/patrones
          PKG="$(ls -1 patrones-*.tgz | tail -n 1)"
          echo "CHART_PKG=$PKG" >> $GITHUB_ENV
          echo "Empaquetado: $PKG"

      - name: Checkout helm-chart repo (GitHub Pages)
        uses: actions/checkout@v3
        with:
          repository: ritatrcr/helm-chart
          token: ${{ secrets.PAT_HELMCHART }}
          path: helm-chart

      - name: Copy packaged chart to helm-chart repo
        shell: bash
        run: |
          set -e
          cp "manifiestos/${{ env.CHART_PKG }}" helm-chart/
          ls -lah helm-chart

      - name: Update Helm repo index (merge)
        shell: bash
        run: |
          set -e
          cd helm-chart
          if [ -f index.yaml ]; then
            helm repo index . --url https://ritatrcr.github.io/helm-chart/ --merge index.yaml
          else
            helm repo index . --url https://ritatrcr.github.io/helm-chart/
          fi
          cat index.yaml | head -n 40

      - name: Commit and push changes to helm-chart repo
        shell: bash
        run: |
          set -e
          cd helm-chart
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git pull --rebase || true
          git add .
          git commit -m "Publish chart patrones ${CHART_VERSION}" || echo "No commit needed"
          git push origin main